# Generated by Django 5.2.12 on 2026-03-16 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=191)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GpsZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('zone_type', models.CharField(choices=[('AUTORISEE', 'Autorisee'), ('INTERDITE', 'Interdite')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('shape_type', models.CharField(choices=[('CIRCLE', 'Circle'), ('POLYGON', 'Polygon')], default='CIRCLE', max_length=20)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GpsAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('SPEEDING', 'Speeding'), ('LOW_BATTERY', 'Low battery'), ('SIGNAL_LOST', 'Signal lost'), ('OUT_OF_ZONE', 'Out of zone')], max_length=40)),
                ('message', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='gps.gpsdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GpsZoneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.gpsdevice')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.gpszone')),
            ],
            options={
                'unique_together': {('zone', 'device')},
            },
        ),
        migrations.AddField(
            model_name='gpszone',
            name='devices',
            field=models.ManyToManyField(related_name='zone_links', through='gps.GpsZoneDevice', to='gps.gpsdevice'),
        ),
        migrations.CreateModel(
            name='GpsLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('gps_timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gps.gpsdevice')),
            ],
            options={
                'ordering': ['-gps_timestamp'],
                'indexes': [models.Index(fields=['device', 'gps_timestamp'], name='gps_gpsloca_device__bf9be2_idx')],
            },
        ),
    ]
