# Generated by Django 5.2.12 on 2026-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('establishment_name', models.CharField(blank=True, default='', max_length=191)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(default='Bujumbura', max_length=128)),
                ('country', models.CharField(default='Burundi', max_length=128)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='BIF', max_length=16)),
                ('tax_rate', models.FloatField(default=18)),
                ('fiscal_year_start', models.CharField(default='01', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stock_low_alert', models.BooleanField(default=True)),
                ('checkout_reminder', models.BooleanField(default=True)),
                ('missing_cash_close', models.BooleanField(default=True)),
                ('daily_auto_summary', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
